"""Generate repository navigation from actual source files and authorities."""
from __future__ import annotations

import argparse
import os
from pathlib import Path

from runtime_common import ROOT, load_document

EXCLUDED = {".git", ".venv", "__pycache__", ".pytest_cache", "local-runs", "outputs", "slprj"}
INDEXES = {"REPOSITORY_INDEX.md", "SKILL_FILE_INDEX.md"}


def source_paths(root: Path) -> list[str]:
    paths = set()
    for directory, subdirectories, files in os.walk(root):
        subdirectories[:] = [name for name in subdirectories if name not in EXCLUDED]
        for name in files:
            path = Path(directory) / name
            if path.is_file():
                paths.add(path.relative_to(root).as_posix())
    return sorted(paths | INDEXES)


def render_indexes(root: Path = ROOT) -> dict[str, str]:
    manifest = load_document(root / "manifest.yaml")
    modules = load_document(root / "core/module_manifest.yaml")["modules"]
    authorities = "\n".join(f"- [{path}]({path})" for path in manifest["active_authorities"])
    module_rows = "\n".join(f"| {name} | {module['phase']} | {module['status']} |"
                            for name, module in modules.items())
    repository = f"""# Repository Index

Generated by `python scripts/generate_indexes.py`; edit the source contracts.

Version: `{manifest['version']}`. Implemented capabilities are listed below; problem audit and model design grant no numerical or business simulation permission.
Repository phase completion still requires PR review, CI, merge and evidence read-back.

## Development authority

[Full implementation plan](docs/V1_FULL_IMPLEMENTATION_PLAN.md) governs development.
[Roadmap](docs/V1_IMPLEMENTATION_ROADMAP.md) is its summary.

## Active authorities

{authorities}

## Module availability

| Capability | Phase | Availability |
|---|---|---|
{module_rows}

Deferred capabilities grant no execution permission and activate no resources.
See [all source files](SKILL_FILE_INDEX.md) for scripts, contracts and tests.
"""
    files = "# Skill File Index\n\nGenerated from actual source files by `python scripts/generate_indexes.py`.\n\n"
    files += "\n".join(f"- [{path}]({path})" for path in source_paths(root)) + "\n"
    return {"REPOSITORY_INDEX.md": repository, "SKILL_FILE_INDEX.md": files}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, content in render_indexes().items():
        path = ROOT / name
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("Stale generated indexes: " + ", ".join(stale))
    elif args.check:
        print("Generated indexes are current.")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
